### PR TITLE
fixed: cannot use redis.Z literal (type redis.Z) as type *redis.Z in …

### PR DESCRIPTION
**Pull request by viruthagiri**
…argument to pipe.ZAdd

### CODE REVIEW

**Comment by thoas** [comment]
It seems it's related to a latest change in `go-redis`, you need to bump the dependency too in `go.mod`, tests are failing.

Thank you for your PR

**Comment by viruthagiri** [comment]
I'm new to go modules. While I can bump the dependency in go.mod file, I'm not sure how go.sum generates cryptographic hashes.  

I have added only one character in the pull. So please close this pull and push from your side.

Thanks

**Comment by thoas** [comment]
let's do this.

**Comment by thoas** [comment]
looks like the change is only available in the current upstream.

Bokchoy will still rely on git tag, so best way to avoid this issue is to use [v6.15.6](https://github.com/go-redis/redis/releases/tag/v6.15.6)

**Comment by viruthagiri** [comment]
Thanks for the update.

**Pull request closed without merging**
